# Generated by Django 4.2.1 on 2023-05-28 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cNumber', models.CharField(default='', max_length=50)),
                ('cAuther', models.CharField(max_length=20)),
                ('cDepartment', models.CharField(max_length=50)),
                ('cType', models.CharField(default=' ', max_length=10)),
                ('cProgress', models.CharField(default='', max_length=20)),
                ('cDate', models.DateField()),
                ('cEndDate', models.DateField(blank=True, null=True)),
                ('cLock', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Signed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cNumber', models.CharField(default='', max_length=50)),
                ('cType', models.CharField(default='簽呈', max_length=10)),
                ('cDepartment', models.CharField(blank=True, max_length=50)),
                ('cAuther', models.CharField(max_length=20)),
                ('cDate', models.DateField()),
                ('cJob_title', models.CharField(blank=True, max_length=50)),
                ('cSubject', models.CharField(default='', max_length=255)),
                ('cDiscription', models.TextField(blank=True)),
                ('home', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='testapp.home')),
            ],
        ),
    ]
