# Generated by Django 4.2.1 on 2023-05-29 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_remove_home_clock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cMeetingType', models.CharField(max_length=10)),
                ('cLocation', models.CharField(blank=True, max_length=30)),
                ('cLeader', models.CharField(max_length=10)),
                ('cRecoder', models.CharField(max_length=10)),
                ('cTopic', models.CharField(max_length=50)),
                ('cAttendees1', models.TextField(blank=True)),
                ('cAttendees2', models.TextField(blank=True)),
                ('cViceGeneral_Sign', models.CharField(blank=True, max_length=20)),
                ('cManger_Sign', models.CharField(blank=True, max_length=20)),
                ('home', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='testapp.home')),
            ],
        ),
        migrations.RemoveField(
            model_name='signed',
            name='cAuther',
        ),
        migrations.RemoveField(
            model_name='signed',
            name='cDate',
        ),
        migrations.RemoveField(
            model_name='signed',
            name='cDepartment',
        ),
        migrations.RemoveField(
            model_name='signed',
            name='cNumber',
        ),
        migrations.RemoveField(
            model_name='signed',
            name='cType',
        ),
        migrations.CreateModel(
            name='MeetingInner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cContent', models.TextField(blank=True)),
                ('cDoPerson', models.CharField(blank=True, default='', max_length=30)),
                ('cExpectDate', models.CharField(blank=True, default='', max_length=20)),
                ('cOther', models.TextField(blank=True)),
                ('innermeeting', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='testapp.meeting')),
            ],
        ),
    ]
