# Generated by Django 4.2.1 on 2023-05-30 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_meeting_cnumber_meeting_ctime_signed_cnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cNumber', models.CharField(default='', max_length=50)),
                ('cAutherManager', models.CharField(blank=True, max_length=20)),
                ('cDecisionDep', models.CharField(max_length=50)),
                ('cImplementDep', models.CharField(max_length=50)),
                ('cSubject', models.TextField()),
                ('cDiscription', models.TextField(blank=True)),
                ('cOption', models.TextField(blank=True)),
                ('home', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='testapp.home')),
            ],
        ),
    ]
