# Generated by Django 4.2.1 on 2023-05-30 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_contract_contractinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='cUndertaker',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='cConfirm',
            field=models.CharField(default='_年_月_日決定以___元整交由__承攬本工程', max_length=100),
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cNumber', models.CharField(default='', max_length=50)),
                ('cProjectName', models.CharField(default='', max_length=50)),
                ('cChangeitem', models.CharField(max_length=20)),
                ('cChangereason', models.CharField(max_length=20)),
                ('cHowChange', models.CharField(max_length=10)),
                ('cAffectitem', models.TextField()),
                ('cRisk', models.TextField()),
                ('cKeypoint', models.TextField()),
                ('cOption_FS', models.TextField()),
                ('cOption_Design', models.TextField()),
                ('cOption_Quality', models.TextField()),
                ('cOption_Purchase', models.TextField()),
                ('cCC', models.CharField(blank=True, max_length=10)),
                ('cTech_bulletin', models.CharField(max_length=5)),
                ('cApproved', models.CharField(blank=True, max_length=20)),
                ('cReview', models.CharField(blank=True, max_length=20)),
                ('cUndertaker', models.CharField(blank=True, max_length=20)),
                ('cFs_Sign', models.CharField(blank=True, max_length=5)),
                ('cDesign_Sign', models.CharField(blank=True, max_length=5)),
                ('cQuality_Sign', models.CharField(blank=True, max_length=5)),
                ('cPurchase_Sign', models.CharField(blank=True, max_length=5)),
                ('home', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='testapp.home')),
            ],
        ),
    ]
