# Generated by Django 4.2.1 on 2023-05-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_contract_cundertaker_alter_contract_cconfirm_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='cConfirm',
            field=models.TextField(blank=True, default='_年_月_日決定以___元整交由__承攬本工程'),
        ),
    ]
