# Generated by Django 4.2.1 on 2023-05-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_alter_contract_cconfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='cEarn',
            field=models.CharField(default='', max_length=10),
        ),
    ]
