# Generated by Django 4.2.1 on 2023-06-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_change_cearn'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='cLock',
            field=models.CharField(default='否', max_length=5),
        ),
    ]
