# Generated by Django 4.2.1 on 2023-06-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_home_clock'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='cDoc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
