# Generated by Django 4.2.1 on 2023-06-09 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_home_cdoc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='cDoc',
            new_name='cReceive',
        ),
    ]
