# Generated by Django 4.2.1 on 2023-06-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_rename_cdoc_home_creceive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='cReceive',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
