# Generated by Django 4.2.1 on 2023-06-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_home_cfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='cCheckuplaod',
            field=models.CharField(default='否', max_length=5),
        ),
    ]
