# Generated by Django 4.2.1 on 2023-06-09 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_home_ccheckuplaod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='cCheckuplaod',
        ),
    ]
