# Generated by Django 4.2.1 on 2023-07-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_remove_home_ccheckuplaod'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='cCheck',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='home',
            name='cProposed',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='cDepartment',
            field=models.CharField(choices=[('總經理室', '總經理室'), ('稽核室', '稽核室'), ('文管中心', '文管中心'), ('管理部', '管理部'), ('業務設計部', '業務設計部'), ('廠務部', '廠務部')], max_length=50),
        ),
        migrations.AlterField(
            model_name='home',
            name='cProgress',
            field=models.CharField(choices=[('草稿', '草稿'), ('流程中', '流程中'), ('廢單', '廢單'), ('結案', '結案')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='home',
            name='cReceive',
            field=models.CharField(blank=True, choices=[('None', '無'), ('郭文龍', '郭文龍'), ('侯國興', '侯國興'), ('郭文河', '郭文河'), ('高晟琅', '高晟琅'), ('黃睿堂', '黃睿堂'), ('鄭任雯', '鄭任雯'), ('高麗華', '高麗華'), ('侯宗仁', '侯宗仁'), ('黃美禎', '黃美禎'), ('江水木', '江水木'), ('吳建進', '吳建進'), ('王韋盛', '王韋盛'), ('陳佳欣', '陳佳欣'), ('蔡孟亭', '蔡孟亭'), ('馮文明', '馮文明'), ('陳恆瑞', '陳恆瑞'), ('郭文欽', '郭文欽'), ('陳春能', '陳春能'), ('黃春北', '黃春北')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='cType',
            field=models.CharField(choices=[('簽呈', '簽呈'), ('會議記錄', '會議記錄'), ('內部連絡單', '內部連絡單'), ('工程發包議價記錄單', '工程發包議價記錄單'), ('設計變更通知單', '設計變更通知單')], default=' ', max_length=10),
        ),
    ]
