# Generated by Django 4.2.1 on 2023-07-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0017_home_ccheck_home_cproposed_alter_home_cdepartment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='cCheck',
        ),
        migrations.RemoveField(
            model_name='home',
            name='cProposed',
        ),
        migrations.AddField(
            model_name='signed',
            name='cCheck',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='signed',
            name='cProposed',
            field=models.TextField(blank=True),
        ),
    ]
