# Generated by Django 4.2.1 on 2023-07-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0019_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='returned',
            name='cTransfer',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
