# Generated by Django 4.2.1 on 2023-07-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0021_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='cCount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
