# Generated by Django 4.2.1 on 2023-07-30 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0022_home_ccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='cCount',
        ),
    ]
