# Generated by Django 4.2.1 on 2023-07-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0023_remove_home_ccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='returned',
            name='chow',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
