# Generated by Django 4.2.1 on 2023-07-30 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0024_returned_chow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returned',
            name='chow',
        ),
    ]
