# Generated by Django 4.2.1 on 2023-08-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0025_remove_returned_chow'),
    ]

    operations = [
        migrations.AddField(
            model_name='returned',
            name='cHow',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
