# Generated by Django 4.2.1 on 2023-09-06 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0027_alter_home_creceive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signed',
            name='cCheck',
        ),
    ]
