# Generated by Django 4.2.1 on 2023-09-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0029_remove_change_capproved_remove_change_creview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='cTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='returned',
            name='cTime',
            field=models.DateTimeField(null=True),
        ),
    ]
