# Generated by Django 4.2.1 on 2023-09-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0031_alter_home_ctime_alter_returned_ctime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='cTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
