# Generated by Django 4.2.1 on 2023-09-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0036_remove_home_ctime'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='cTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
