# Generated by Django 4.2.1 on 2023-09-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0040_alter_home_creceive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='cCount',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
