# Generated by Django 4.2.1 on 2023-11-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0044_remove_returned_returneddate_contractinner_cnumber_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='change',
            table='Changes',
        ),
    ]
