# Generated by Django 4.2.7 on 2023-11-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0045_alter_change_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinginner',
            name='cNumber',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
