# Generated by Django 4.2.7 on 2023-11-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0046_alter_meetinginner_cnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returned',
            name='cNumber',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
