# Generated by Django 4.2.7 on 2023-11-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0048_rename_ctime_returned_creturnedtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='cTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
