# Generated by Django 4.2.1 on 2024-01-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0049_alter_home_ctime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change',
            name='ChangeDate',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='ContactDate',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='ContractDate',
        ),
        migrations.RemoveField(
            model_name='contractinner',
            name='ContractInnerDate',
        ),
        migrations.RemoveField(
            model_name='home',
            name='HomeTime',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='MeetingDate',
        ),
        migrations.RemoveField(
            model_name='meetinginner',
            name='MeetingInnerDate',
        ),
        migrations.RemoveField(
            model_name='signed',
            name='SignedDate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='UserTime',
        ),
    ]
