# Generated by Django 4.2.1 on 2024-01-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0050_remove_change_changedate_remove_contact_contactdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='cProgress',
            field=models.CharField(choices=[('草稿', '草稿'), ('流程中', '流程中'), ('結案', '結案')], default='草稿', max_length=20),
        ),
        migrations.AlterField(
            model_name='home',
            name='cType',
            field=models.CharField(choices=[('簽呈', '簽呈'), ('會議記錄表', '會議記錄表'), ('內部連絡單', '內部連絡單'), ('發包議價表', '發包議價表'), ('設計變更通知單', '設計變更通知單')], default=' ', max_length=10),
        ),
    ]
