# Generated by Django 4.2.1 on 2024-01-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0052_alter_transfered_ctransferto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signed',
            name='cSubject',
        ),
        migrations.AddField(
            model_name='home',
            name='cSubject',
            field=models.CharField(default='', max_length=255),
        ),
    ]
