# Generated by Django 4.2.1 on 2024-01-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0054_signed_csubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signed',
            name='cSubject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
