# Generated by Django 4.2.1 on 2024-01-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0055_alter_signed_csubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='signed',
            name='cSecret',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
