# Generated by Django 4.2.1 on 2024-01-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0056_signed_csecret'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='cSecret',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
