# Generated by Django 4.2.1 on 2024-01-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0057_home_csecret'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfered',
            name='cNumber',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
