# Generated by Django 4.2.1 on 2024-01-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0058_transfered_cnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinginner',
            name='cFile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='home',
            name='cProgress',
            field=models.CharField(default='草稿', max_length=20),
        ),
        migrations.AlterField(
            model_name='home',
            name='cType',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
