# Generated by Django 4.2.1 on 2024-01-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0059_meetinginner_cfile_alter_home_cprogress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetinginner',
            name='cOther',
        ),
        migrations.AddField(
            model_name='meetinginner',
            name='cStartDate',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
