# Generated by Django 4.2.1 on 2024-01-27 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0060_remove_meetinginner_cother_meetinginner_cstartdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cNumber', models.CharField(blank=True, default='', max_length=50)),
                ('cPurpose', models.TextField(blank=True)),
                ('cPerson', models.CharField(blank=True, default='', max_length=30)),
                ('cDate', models.DateField(blank=True, null=True)),
                ('cFile', models.FileField(blank=True, null=True, upload_to='')),
                ('purposemeeting', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='testapp.meetinginner')),
            ],
            options={
                'db_table': 'MeetingPurpose',
            },
        ),
    ]
