# Generated by Django 4.2.1 on 2024-01-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0061_meetingpurpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='cUndertaker',
        ),
    ]
