# Generated by Django 4.2.1 on 2024-01-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0062_remove_contract_cundertaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='cDepartment',
            field=models.CharField(choices=[('總經理室', '總經理室'), ('副總經理室', '副總經理室'), ('海外事業部', '海外事業部'), ('協理室', '協理室'), ('文管中心', '文管中心'), ('管理部', '管理部'), ('業務設計部', '業務設計部'), ('廠務部', '廠務部'), ('品管課', '品管課'), ('設計生技課', '設計生技課'), ('業務課', '業務課'), ('工程課', '工程課'), ('生管課', '生管課'), ('採購課', '採購課'), ('製造課', '製造課'), ('財會課', '財會課'), ('人資總務課', '人資總務課')], max_length=50),
        ),
        migrations.AlterField(
            model_name='home',
            name='cProgress',
            field=models.CharField(choices=[('草稿', '草稿'), ('流程中', '流程中'), ('結案', '結案'), ('駁回', '駁回')], default='草稿', max_length=20),
        ),
        migrations.AlterField(
            model_name='home',
            name='cType',
            field=models.CharField(choices=[('簽呈', '簽呈'), ('會議記錄表', '會議記錄表'), ('內部連絡單', '內部連絡單'), ('發包議價表', '發包議價表'), ('設計變更通知單', '設計變更通知單')], default=' ', max_length=10),
        ),
    ]
