# Generated by Django 4.2.1 on 2024-03-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0064_alter_transfered_ctransferto'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='cFile1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='home',
            name='cFile2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='home',
            name='cFile3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='home',
            name='cFile4',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
