# Generated by Django 4.2.1 on 2024-04-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0065_home_cfile1_home_cfile2_home_cfile3_home_cfile4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Starttime', models.CharField(default='', max_length=255)),
                ('Endtime', models.CharField(default='', max_length=255)),
                ('agent_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Agent',
            },
        ),
    ]
