# Generated by Django 4.2.1 on 2024-04-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0066_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='old_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
