# Generated by Django 4.2.1 on 2024-04-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0067_agent_old_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='Endtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='Starttime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
