# Generated by Django 4.2.1 on 2024-04-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0068_alter_agent_endtime_alter_agent_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='Endtime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='Starttime',
            field=models.DateTimeField(),
        ),
    ]
