# Generated by Django 4.2.1 on 2024-04-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0069_alter_agent_endtime_alter_agent_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='Endtime',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='Starttime',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
