# Generated by Django 4.2.1 on 2024-04-07 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0070_alter_agent_endtime_alter_agent_starttime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
