# Generated by Django 4.2.1 on 2024-04-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0071_delete_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Starttime', models.CharField(blank=True, default='', max_length=255)),
                ('Endtime', models.CharField(blank=True, default='', max_length=255)),
                ('old_name', models.CharField(default='', max_length=20)),
                ('agent_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Agent',
            },
        ),
    ]
