# Generated by Django 4.2.1 on 2024-04-07 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0074_agent_perchange_delete_pchange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
