# Generated by Django 4.2.1 on 2024-04-07 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0075_delete_agent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='perchange',
            new_name='person',
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
